[flake8-black]
src.pypi = "flake8-black"
fetch.pypi = "flake8-black"

[flake8-deprecated]
src.pypi = "flake8-deprecated"
fetch.pypi = "flake8-deprecated"

[flake8-isort]
src.pypi = "flake8-isort"
fetch.pypi = "flake8-isort"
